apiVersion: apps/v1
kind: Replicaset
metadata:
  labels:
    app: metadata-service
  name: liveness-exec
spec:
  containers:
  - name: metadata
    image: metadata:1.0
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5
      periodSeconds: 5